name: Keith Marcel
favicon: null
layout_spectrum: 0.15991230821236968
typography_spectrum: 0.2709924343507737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8284456403926015
  lightness: 0.9457259390037507
  saturation: 0.6404141946695745
  rhythmicContrast: 0.8773165612947196
purpose: []
